
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `semi1practica1` DEFAULT CHARACTER SET utf8 ;
USE `semi1practica1` ;

CREATE TABLE IF NOT EXISTS `semi1practica1`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(200) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `linkFotoPerfil` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idUsuario`));

CREATE TABLE IF NOT EXISTS `semi1practica1`.`Album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  INDEX `FK_idalbum_idusuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `FK_idalbum_idusuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `semi1practica1`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE IF NOT EXISTS `semi1practica1`.`Foto` (
  `idFoto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `idAlbum` INT NOT NULL,
  PRIMARY KEY (`idFoto`),
  INDEX `FK_foto_idalbum_idx` (`idAlbum` ASC) VISIBLE,
  CONSTRAINT `FK_foto_idalbum`
    FOREIGN KEY (`idAlbum`)
    REFERENCES `semi1practica1`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
